version: "3.6"

services:
  app:
    container_name: ${CONTAINER_PREFIX}_app
    build: ./docker/app
    volumes:
      - .:/app
    networks:
      - assignment
    ports:
      - 80

  mysql:
    container_name: ${CONTAINER_PREFIX}_mysql
    image: mysql:5.7
    networks:
      - assignment
    ports:
      - 3306

networks:
  assignment:
    labels:
      - "spendesk_assignment"
